name: eks
path: git::https://github.com/awslabs/idf-modules.git//modules/compute/eks?ref=release/1.1.0&depth=1
dataFiles:
  - filePath: data/eks_dockerimage-replication/versions/1.25.yaml
  - filePath: data/eks_dockerimage-replication/versions/default.yaml
parameters:
  - name: replicated-ecr-images-metadata-s3-path
    valueFrom:
      moduleMetadata:
        group: replication
        name: replication
        key: s3_full_path
  - name: vpc-id
    valueFrom:
      moduleMetadata:
        group: optionals
        name: networking
        key: VpcId
  - name: controlplane-subnet-ids
    valueFrom:
      moduleMetadata:
        group: optionals
        name: networking
        key: PrivateSubnetIds
  - name: dataplane-subnet-ids
    valueFrom:
      moduleMetadata:
        group: optionals
        name: networking
        key: PrivateSubnetIds
  - name: eks-admin-role-name
    value: Admin
  - name: eks-poweruser-role-name
    value: PowerUser
  - name: eks-read-only-role-name
    value: ReadOnly
  - name: eks-version
    value: "1.25"
    # valueFrom:
    #   envVariable: GLOBAL_EKS_VERSION
  - name: eks-compute
    value:
      eks_nodegroup_config:
        - eks_ng_name: ng1
          eks_node_quantity: 2
          eks_node_max_quantity: 5
          eks_node_min_quantity: 1
          eks_node_disk_size: 20
          eks_node_instance_type: "m5.large"
        - eks_ng_name: ng2
          eks_node_quantity: 2
          eks_node_max_quantity: 5
          eks_node_min_quantity: 1
          eks_node_disk_size: 20
          eks_node_instance_type: "m5.xlarge"
        - eks_ng_name: gpung1
          eks_node_quantity: 1
          eks_node_max_quantity: 3
          eks_node_min_quantity: 1
          eks_node_disk_size: 100
          eks_node_instance_type: "g4dn.xlarge"
          eks_node_labels:
            usage: visualization
      eks_node_spot: False
      eks_secrets_envelope_encryption: False
      eks_api_endpoint_private: False
  - name: eks-addons
    value:
      deploy_aws_lb_controller: True # We deploy it unless set to False
      deploy_external_dns: True # We deploy it unless set to False
      deploy_aws_ebs_csi: True # We deploy it unless set to False
      deploy_aws_efs_csi: True # We deploy it unless set to False
      deploy_aws_fsx_csi: True # We deploy it unless set to False
      deploy_cluster_autoscaler: True # We deploy it unless set to False
      deploy_metrics_server: True # We deploy it unless set to False
      deploy_secretsmanager_csi: True # We deploy it unless set to False
      deploy_external_secrets: False
      deploy_cloudwatch_container_insights_metrics: True # We deploy it unless set to False
      deploy_cloudwatch_container_insights_logs: True
      cloudwatch_container_insights_logs_retention_days: 7
---
name: efs
path: modules/core/efs
targetAccount: primary
targetRegion: us-east-1
parameters:
  - name: vpc-id
    valueFrom:
      moduleMetadata:
        group: optionals
        name: networking
        key: VpcId
  - name: removal-policy
    value: DESTROY
