name: mlops
toolchainRegion: us-east-1
groups:
  - name: optionals
    path: manifests/mlops/optional-modules.yaml
  - name: core
    path: manifests/mlops/core-modules.yaml
  - name: platform
    path: manifests/mlops/kf-modules.yaml
  - name: users
    path: manifests/mlops/kf-users.yaml   
targetAccountMappings:
  - alias: primary
    accountId: 
      valueFrom:
        envVariable: PRIMARY_ACCOUNT
    default: true
    parametersGlobal:
      dockerCredentialsSecret: aws-addf-docker-credentials
    regionMappings:
      - region: us-east-1
        default: true
