name: example-prod
toolchainRegion: us-west-2
groups:
  # - name: optionals
  #   path: manifests/example-prod/optional-modules.yaml
  - name: replication
    path: manifests/example-prod/replicator-modules.yaml
  - name: core
    path: manifests/example-prod/core-modules.yaml
  - name: examples
    path: manifests/example-prod/example-modules.yaml
  - name: rosbag
    path: manifests/example-prod/rosbag-modules.yaml
  - name: simulations
    path: manifests/example-prod/simulation-modules.yaml
  - name: integration
    path: manifests/example-prod/integration-modules.yaml
  # - name: ide
  #   path: manifests/example-prod/ide-modules.yaml
targetAccountMappings:
  - alias: primary
    accountId: 1234567890
    default: true
    parametersGlobal:
      dockerCredentialsSecret: aws-addf-docker-credentials
    regionMappings:
      - region: us-west-2
        default: true
