name: jupyter-hub
path: modules/demo-only/jupyter-hub/
parameters:
  - name: eks-cluster-admin-role-arn
    valueFrom:
      moduleMetadata:
        group: core
        name: eks
        key: EksClusterAdminRoleArn
  - name: eks-cluster-name
    valueFrom:
      moduleMetadata:
        group: core
        name: eks
        key: EksClusterName
  - name: eks-oidc-arn
    valueFrom:
      moduleMetadata:
        group: core
        name: eks
        key: EksOidcArn
  - name: secrets-manager-name
    value: jh-credentials
# ---
# name: vscode
# path: modules/demo-only/vscode-on-eks/
# parameters:
#   - name: eks-cluster-admin-role-arn
#     valueFrom:
#       moduleMetadata:
#         group: core
#         name: eks
#         key: EksClusterAdminRoleArn
#   - name: eks-cluster-name
#     valueFrom:
#       moduleMetadata:
#         group: core
#         name: eks
#         key: EksClusterName
#   - name: eks-oidc-arn
#     valueFrom:
#       moduleMetadata:
#         group: core
#         name: eks
#         key: EksOidcArn
#   - name: secrets-manager-name
#     value: vscode-credentials