name: replication
path: git::https://github.com/awslabs/idf-modules.git//modules/replication/dockerimage-replication?ref=release/1.1.0&depth=1
dataFiles:
  - filePath: data/eks_dockerimage-replication/versions/1.25.yaml
  - filePath: data/eks_dockerimage-replication/versions/default.yaml
parameters:
  - name: eks-version
    value: "1.25"
    # valueFrom:
    #   envVariable: GLOBAL_EKS_VERSION