name: app-reg
path: git::https://github.com/awslabs/idf-modules.git//modules/service-catalog/app-registry
parameters:
  - name: solution-id
    value: id
  - name: solution-name
    value: name
  - name: solution-version
    value: version